AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Provision a python Lambda function

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ssl-checker-lambda
      Handler: lambda_func.lambda_handler
      Runtime: python3.9
      PackageType: Zip
      CodeUri: ../../function/.
      Description: Check passed in host for SSL Cert expiration
      Timeout: 4
      Policies:
        - AWSLambdaBasicExecutionRole
        # - AWSLambda_ReadOnlyAccess